### ISSUE TITLE
Able to change product quantity more than available during checkout

### ISSUE THREAD

**Issue by mazharoddin** [owen2345/camaleon-ecommerce#23]
I am able to change product quantity more than available during checkout, but it should be restricted to currently available product quantity.
<img width="346" alt="screen shot 2016-04-06 at 10 29 50" src="https://cloud.githubusercontent.com/assets/6102465/14306223/8c748cd4-fbe2-11e5-898e-43a92e98e022.png">

<img width="1158" alt="screen shot 2016-04-06 at 10 28 43" src="https://cloud.githubusercontent.com/assets/6102465/14306204/621c172c-fbe2-11e5-9a7c-14f6c8d73a71.png">

**Comment by mazharoddin** [comment]
@owen2345, also I observed that product availability quantity is not changed even after adding products to cart.

**Comment by owen2345** [comment]
Product availability is changed after the cart is paid.

**Comment by mazharoddin** [comment]
ohh ok, Let me test it.

**Comment by mazharoddin** [comment]
Hi @owen2345, 
I have one query, if product availability is changed once payment is done, then how we can avoid two customers trying to add a product at same time, with current design both able to add product to cart, but finally only one customer's checkout will be successful. 
It would be frustrating experience for customer to complete all steps and finally find out product is not in stock.

So I feel its better update the product quantity whenever a customers added a item to cart, if customer didn't complete the transaction in time then revert back the quantity( e.g after 5 minutes).
 What do you feel?

**Comment by mazharoddin** [comment]
@owen2345 , product availability quantity is not changing even after I marked as payment as successful.

**Comment by owen2345** [comment]
I agree with you @mazharoddin

**Comment by owen2345** [comment]
I agree with you @mazharoddin

**Comment by mazharoddin** [comment]
sure @owen2345. Thanks.

**Comment by owen2345** [comment]
Fixed!

**Comment by mazharoddin** [comment]
Great ..thanks @owen2345

**Comment by mazharoddin** [comment]
Hi @owen2345,
Now Product availability is changing after I marked as payment as successful. however the issue I originally reported still persists. i.e I am able to change the order quantity to any number during checkout.

<img width="1152" alt="screen shot 2016-08-27 at 12 27 16 pm" src="https://cloud.githubusercontent.com/assets/6102465/18025776/a1972b0a-6c51-11e6-8b77-f2e755a37b7f.png">

**Comment by owen2345** [comment]
It is strange, I tested again with both kind of products (normal and variations) and works well:
Product available (123):
![screen shot 2016-08-27 at 04 34 52](https://cloud.githubusercontent.com/assets/1148415/18026279/5f8968b4-6c0f-11e6-90cc-9312543131a8.png)

User x: can not update more than 23
![screen shot 2016-08-27 at 04 34 25](https://cloud.githubusercontent.com/assets/1148415/18026280/5f8c9a98-6c0f-11e6-95d7-8998a3cef183.png)

User y: already has been taken 100 items but it still in cart
![screen shot 2016-08-27 at 04 34 07](https://cloud.githubusercontent.com/assets/1148415/18026281/5f8f9572-6c0f-11e6-8946-7317fda7fa0b.png)

**Comment by mazharoddin** [comment]
ohh ok, let me retest, but i am sure it was not working for me..any way thanks for looking it..

**Comment by mazharoddin** [comment]
Not sure, what's the issue, but I am able to change product quantity more than available at checkout.
<img width="748" alt="screen shot 2016-08-27 at 2 57 37 pm" src="https://cloud.githubusercontent.com/assets/6102465/18026510/c195a444-6c66-11e6-920a-89e0e5977d02.png">
<img width="1100" alt="screen shot 2016-08-27 at 2 57 43 pm" src="https://cloud.githubusercontent.com/assets/6102465/18026512/c4319442-6c66-11e6-98bd-7222a2902813.png">

**Comment by owen2345** [comment]
could you share me a repo or publish in heroku?

**Comment by mazharoddin** [comment]
Hi @owen2345 ,
Please find below for the repo, I newly created this repo to create this issue.

https://github.com/mazharoddin/camaleon_cms_debug

**Comment by mazharoddin** [comment]
One more issue I noticed is, user can checkout a product with '0' quantity, finally after completing all steps payment is failing with error related to coupon, but it should be better if we restrict checkout using '0' quantity.
